export const COLOR = {
  PRIMARY: '#0080FF',
  LIGHT_PRIMARY: '#369AFE',
  SEMI_PRIMARY: '#2196F3',
  WHITE: '#FFFFFF',
  LIGHT_BLUE: '#2291FF',
  SAPPHIRE_BLUE: '#242F57',
  WHITE_BLUE: '#97A0C3',
  WHITE_GRAY: '#636E95',
  LIGHT_GRAY: '#FAFCFE',
  LIGHT_WHITE_GRAY: '#DCE9F7',
}

export const FONT = {
  DEFAULT: 'Inter'
}
